# Generated by Django 5.2.8 on 2025-11-13 10:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_brand_image_alter_category_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف (درصد یا مبلغ)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداقل مبلغ خرید')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداکثر مبلغ تخفیف (در صورت درصدی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد تخفیف (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('brands', models.ManyToManyField(blank=True, related_name='discount_baskets', to='products.brand', verbose_name='برندها')),
                ('groups', models.ManyToManyField(blank=True, related_name='discount_baskets', to='products.category', verbose_name='گروه\u200cها')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_baskets', to='products.product', verbose_name='کالاها')),
                ('users', models.ManyToManyField(blank=True, related_name='discount_baskets', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
    ]
