# Generated by Django 5.2.8 on 2025-11-13 18:10

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_iamge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iamge_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر پروفایل'),
        ),
    ]
