# Generated by Django 5.2.8 on 2025-11-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_iamge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='iamge_name',
        ),
    ]
