# Generated by Django 5.2.8 on 2025-11-13 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_brand_image_alter_category_image_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'موجودی محصول', 'verbose_name_plural': 'موجودی محصولات'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش موجودی', 'verbose_name_plural': 'تراکنش\u200cهای موجودی'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'انبار', 'verbose_name_plural': 'انبارها'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=3, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام انبار'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
